#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace PPCT.Models.Dataverse
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class XrmContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public XrmContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.CustomAPI"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.CustomAPI> CustomAPISet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.CustomAPI>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.Entity_Ent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.Entity_Ent> Entity_EntSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.Entity_Ent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.PluginAssembly"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.PluginAssembly> PluginAssemblySet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.PluginAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.pluginpackage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.pluginpackage> pluginpackageSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.pluginpackage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.PluginType"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.PluginType> PluginTypeSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.PluginType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.Publisher"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.Publisher> PublisherSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.Publisher>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessage> SdkMessageSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessageFilter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessageFilter> SdkMessageFilterSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessageFilter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessagePair"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessagePair> SdkMessagePairSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessagePair>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessageProcessingStep"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessageProcessingStepImage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessageProcessingStepImage> SdkMessageProcessingStepImageSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessageProcessingStepImage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SdkMessageProcessingStepSecureConfig"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SdkMessageProcessingStepSecureConfig> SdkMessageProcessingStepSecureConfigSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SdkMessageProcessingStepSecureConfig>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.ServiceEndpoint"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.ServiceEndpoint> ServiceEndpointSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.ServiceEndpoint>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PPCT.Models.Dataverse.SolutionComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PPCT.Models.Dataverse.SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<PPCT.Models.Dataverse.SolutionComponent>();
			}
		}
	}
}
#pragma warning restore CS1591
