#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCT.Models.Dataverse
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("entity")]
	public partial class Entity_Ent : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the entity entity
		/// </summary>
		public partial class Fields
		{
			public const string AddressTableName = "addresstablename";
			public const string BaseTableName = "basetablename";
			public const string CollectionName = "collectionname";
			public const string ComponentState = "componentstate";
			public const string EntityId = "entityid";
			public const string Id = "entityid";
			public const string EntitySetName1 = "entitysetname";
			public const string ExtensionTableName = "extensiontablename";
			public const string ExternalCollectionName = "externalcollectionname";
			public const string ExternalName = "externalname";
			public const string IsActivity = "isactivity";
			public const string LogicalCollectionName = "logicalcollectionname";
			public const string LogicalName1 = "logicalname";
			public const string Name = "name";
			public const string ObjectTypeCode = "objecttypecode";
			public const string OriginalLocalizedCollectionName = "originallocalizedcollectionname";
			public const string OriginalLocalizedName = "originallocalizedname";
			public const string OverwriteTime = "overwritetime";
			public const string ParentControllingAttributeName = "parentcontrollingattributename";
			public const string PhysicalName = "physicalname";
			public const string ReportViewName = "reportviewname";
			public const string SolutionId = "solutionid";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Entity_Ent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "entity";
		
		public const string EntityLogicalCollectionName = "entities";
		
		public const string EntitySetName = "entities";
		
		/// <summary>
		/// The address table name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addresstablename")]
		public string AddressTableName
		{
			get
			{
				return this.GetAttributeValue<string>("addresstablename");
			}
			set
			{
				this.SetAttributeValue("addresstablename", value);
			}
		}
		
		/// <summary>
		/// The base table name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("basetablename")]
		public string BaseTableName
		{
			get
			{
				return this.GetAttributeValue<string>("basetablename");
			}
			set
			{
				this.SetAttributeValue("basetablename", value);
			}
		}
		
		/// <summary>
		/// The collection name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("collectionname")]
		public string CollectionName
		{
			get
			{
				return this.GetAttributeValue<string>("collectionname");
			}
			set
			{
				this.SetAttributeValue("collectionname", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Unique identifier of the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityid")]
		public System.Nullable<System.Guid> EntityId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityid");
			}
			set
			{
				this.SetAttributeValue("entityid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.EntityId = value;
			}
		}
		
		/// <summary>
		/// The entity set name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitysetname")]
		public string EntitySetName1
		{
			get
			{
				return this.GetAttributeValue<string>("entitysetname");
			}
			set
			{
				this.SetAttributeValue("entitysetname", value);
			}
		}
		
		/// <summary>
		/// The extension table name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("extensiontablename")]
		public string ExtensionTableName
		{
			get
			{
				return this.GetAttributeValue<string>("extensiontablename");
			}
			set
			{
				this.SetAttributeValue("extensiontablename", value);
			}
		}
		
		/// <summary>
		/// The external collection name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("externalcollectionname")]
		public string ExternalCollectionName
		{
			get
			{
				return this.GetAttributeValue<string>("externalcollectionname");
			}
			set
			{
				this.SetAttributeValue("externalcollectionname", value);
			}
		}
		
		/// <summary>
		/// The external name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("externalname")]
		public string ExternalName
		{
			get
			{
				return this.GetAttributeValue<string>("externalname");
			}
			set
			{
				this.SetAttributeValue("externalname", value);
			}
		}
		
		/// <summary>
		/// Whether this entity is of type activity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isactivity")]
		public System.Nullable<bool> IsActivity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isactivity");
			}
		}
		
		/// <summary>
		/// The logical collection name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("logicalcollectionname")]
		public string LogicalCollectionName
		{
			get
			{
				return this.GetAttributeValue<string>("logicalcollectionname");
			}
			set
			{
				this.SetAttributeValue("logicalcollectionname", value);
			}
		}
		
		/// <summary>
		/// The logical name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("logicalname")]
		public string LogicalName1
		{
			get
			{
				return this.GetAttributeValue<string>("logicalname");
			}
			set
			{
				this.SetAttributeValue("logicalname", value);
			}
		}
		
		/// <summary>
		/// The name of this Entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// The object type code of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public System.Nullable<int> ObjectTypeCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("objecttypecode");
			}
		}
		
		/// <summary>
		/// The original localized collection name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originallocalizedcollectionname")]
		public string OriginalLocalizedCollectionName
		{
			get
			{
				return this.GetAttributeValue<string>("originallocalizedcollectionname");
			}
			set
			{
				this.SetAttributeValue("originallocalizedcollectionname", value);
			}
		}
		
		/// <summary>
		/// The original localized name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originallocalizedname")]
		public string OriginalLocalizedName
		{
			get
			{
				return this.GetAttributeValue<string>("originallocalizedname");
			}
			set
			{
				this.SetAttributeValue("originallocalizedname", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// The parent controlling attribute name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcontrollingattributename")]
		public string ParentControllingAttributeName
		{
			get
			{
				return this.GetAttributeValue<string>("parentcontrollingattributename");
			}
			set
			{
				this.SetAttributeValue("parentcontrollingattributename", value);
			}
		}
		
		/// <summary>
		/// The physical name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("physicalname")]
		public string PhysicalName
		{
			get
			{
				return this.GetAttributeValue<string>("physicalname");
			}
			set
			{
				this.SetAttributeValue("physicalname", value);
			}
		}
		
		/// <summary>
		/// The Report view name of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reportviewname")]
		public string ReportViewName
		{
			get
			{
				return this.GetAttributeValue<string>("reportviewname");
			}
			set
			{
				this.SetAttributeValue("reportviewname", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// The version number of this entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
}
#pragma warning restore CS1591
